version: '3'

services:
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        ports:
            - "${HEIMDALL_PORT_HTTP}:80"
            - "${HEIMDALL_PORT_HTTPS}:443"
        volumes:
            - ${HEIMDALL_CONFIG}:/config
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "${PIHOLE_PORT}:80"
            - "443:443"
        environment:
            - WEBPASSWORD=${PIHOLE_ADMIN_PASSWORD}
        volumes:
            - ${PIHOLE_DATA}:/etc/pihole
            - ${PIHOLE_CONFIG}:/etc/dnsmasq.d
