version: '3'

services:
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        env_file: defaults.env
        ports:
            - "${HEIMDALL_PORT_HTTP}:80"
            - "${HEIMDALL_PORT_HTTPS}:443"
        volumes:
            - ${HEIMDALL_CONFIG}:/config
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        env_file: defaults.env
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "${PIHOLE_PORT_HTTP}:80"
            - "${PIHOLE_PORT_HTTPS}:443"
        environment:
            - WEBPASSWORD=${PIHOLE_ADMIN_PASSWORD}
        volumes:
            - ${PIHOLE_DATA}:/etc/pihole
            - ${PIHOLE_CONFIG}:/etc/dnsmasq.d
    homeassistant:
        image: "ghcr.io/home-assistant/home-assistant:stable"
        container_name: home-assistant
        restart: unless-stopped
        env_file: defaults.env
        network_mode: host
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        volumes:
            - ${HA_DIR}/config:/config
            - ${HA_DIR}/etc/localtime:/etc/localtime:ro
            - ${HA_DIR}/run/dbus:/run/dbus:ro
        privileged: true
