version: '3'
services:
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        ports:
            - "${HEIMDALL_PORT_HTTP}:80"
            - "${HEIMDALL_PORT_HTTPS}:443"
        volumes:
            - ${HEIMDALL_DIR}/config:/config
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        user: ${LOCAL_USER}:${LOCAL_USER}
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "${PIHOLE_PORT_HTTP}:80"
            - "${PIHOLE_PORT_HTTPS}:443"
        environment:
            - TZ=${TZ}
            - WEBPASSWORD=${PIHOLE_ADMIN_PASSWORD}
        volumes:
            - ${PIHOLE_DIR}/etc/pihole:/etc/pihole
            - ${PIHOLE_DIR}/etc/dnsmasq.d:/etc/dnsmasq.d
        user: ${LOCAL_USER}:${LOCAL_USER}
    homeassistant:
        image: "ghcr.io/home-assistant/home-assistant:stable"
        container_name: home-assistant
        restart: unless-stopped
        network_mode: host
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        volumes:
            - ${HA_DIR}/config:/config
            - ${HA_DIR}/etc/localtime:/etc/localtime:ro
            - ${HA_DIR}/run/dbus:/run/dbus:ro
        privileged: true
        user: ${LOCAL_USER}:${LOCAL_USER}
