version: '3'
services:
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        ports:
            - "${HEIMDALL_PORT_HTTP}:80"
            - "${HEIMDALL_PORT_HTTPS}:443"
        volumes:
            - ${HEIMDALL_DIR}/config:/config
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "${PIHOLE_PORT_HTTP}:80"
            - "${PIHOLE_PORT_HTTPS}:443"
        environment:
            - TZ=${TZ}
            - WEBPASSWORD=${PIHOLE_ADMIN_PASSWORD}
            - PIHOLE_UID=${PUID}
            - PIHOLE_GID=${PGID}
        volumes:
            - ${PIHOLE_DIR}/etc/pihole:/etc/pihole
            - ${PIHOLE_DIR}/etc/dnsmasq.d:/etc/dnsmasq.d
        dns:
            - 127.0.0.1
            - 1.1.1.2
    homeassistant:
        image: "ghcr.io/home-assistant/home-assistant:stable"
        container_name: home-assistant
        restart: unless-stopped
        network_mode: host
        environment:
            - TZ=${TZ}
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        volumes:
            - ${HA_DIR}/config:/config
            - ${HA_DIR}/etc/localtime:/etc/localtime:ro
            - ${HA_DIR}/run/dbus:/run/dbus:ro
        privileged: true
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: unless-stopped
        environment:
            - TZ=${TZ}
        ports:
            - "${INFLUXDB_PORT}:8086"
        volumes:
            - ${INFLUXDB_DIR}/var/lib/influxdb2:/var/lib/influxdb2
    mariadb:
        image: mariadb
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            HA_DB_PASSWORD: ${HA_DB_PASSWORD}
        volumes:
            - ./mariadb/init:/docker-entrypoint-initdb.d
            - ${MARIADB_DIR}/data:/var/lib/mysql
        ports:
            - ${MARIADB_PORT}:3306
